### ISSUE TITLE
Certain B9 parts looking split

### ISSUE THREAD

**Issue by barakiel011** [blowfishpro/B9-Aerospace#103]
Several of the parts I try to build with come out “duck billed shaped”. I’ve also found parts with odd texturing. I’ve installed multiple times to try and fix the issue and I have not found it come up with anyone else to see how they solved it.

Here the list of parts in particular:
HL 8m universal tail
Mk1 universal tail section
Mk1b nosecone (long) and (short)
Mk2 m125 fuselage adapter
Mk2b nosecone (long) and (short)
S2 Universal tail section
Mk2 2m and 5m fuselage universal 
Mk1 5m and 2m fuselage universal

In all instances, I only select the one part but it looks like it’s outputting as two.

**Comment by barakiel011** [comment]
![78516558-37D0-42B4-81DA-817C5C48896E](https://user-images.githubusercontent.com/68605693/88079370-9ae66e80-cb4b-11ea-998c-e745ac77afd5.jpeg)
![Uploading 423D9B66-28D7-4182-8DC1-398DDC174CCF.jpeg…]()

**Comment by barakiel011** [comment]
![Uploading 4B39AF07-C002-4D05-B1C9-DBC75022C3B8.jpeg…]()

**Comment by blowfishpro** [comment]
B9PartSwitch is either not installed or not working correctly.  Verify that all the dependencies are up to date.

**Comment by barakiel011** [comment]
B9partswitch is installed. Just finished a reinstall on it. Same issue.

**Comment by barakiel011** [comment]
Update. I did a full reinstall of my game and then reinstalled b9 aerospace and b9 part switch. I’m getting the same result with parts mention beforehand.

**Comment by blowfishpro** [comment]
In that case I need logs as usual.

**Comment by barakiel011** [comment]
[MMPatch.log](https://github.com/blowfishpro/B9-Aerospace/files/4976204/MMPatch.log)
[ModuleManager.log](https://github.com/blowfishpro/B9-Aerospace/files/4976205/ModuleManager.log)

**Comment by barakiel011** [comment]
if you need other logs let me know

**Comment by blowfishpro** [comment]
I'll need KSP's main log.  ModuleManager shows that the directory is there but the plugin is either missing or not loading, either way that information will be in the main log.

**Comment by barakiel011** [comment]
[KSP.log](https://github.com/blowfishpro/B9-Aerospace/files/4976986/KSP.log)

**Comment by blowfishpro** [comment]
Are you sure the plugin is there?  KSP doesn't seem to be detecting anything.  Should be at `GameData/B9PartSwitch/Plugins/B9PartSwitch.dll`

**Comment by barakiel011** [comment]
it doesn't look like its there. I looked through the zip file I downloaded and it wasn't there as well

**Comment by blowfishpro** [comment]
Well not sure where you got it from, but it needs to be there.  The release packages for B9PartSwitch include the DLL.  Don't just download the repo, as that doesn't have it.

**Comment by barakiel011** [comment]
I pulled b9partswitch from your repository on github

**Comment by barakiel011** [comment]
Got a better recommendation from where to pull it from?

**Comment by barakiel011** [comment]
Never mind I found what you meant on the release. I’ll try loading it tonight.
