### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by HittmanA** [blowfishpro/B9-Aerospace#19]
I don't understand what the file structure of the GameData folder is supposed to be. Can someone give me an example please?

**Comment by blowfishpro** [comment]
Your GameData folder should have the same structure as the GameData folder in the download.

```
- KSP.exe
+ KSP_Data
+ GameData
  + Squad
  + B9_Aerospace
  + B9AnimationModules
  + B9PartSwitch
  + Firespitter
  + JSI
  + SmokeScreen
  + B9_Aerospace_Legacy // optional
  + B9_Aerospace_HX // optional
  - ModuleManager.2.6.24.dll // or whatever the latest is

**Comment by blowfishpro** [comment]
I don't think there's anything actionable in this issue so I'm going to close it. You can still comment on it if you have remaining questions on the installation procedure.
