### ISSUE TITLE
FAR reports +ve Xu on S2 parts

### ISSUE THREAD

**Issue by ZirconiumX** [blowfishpro/B9-Aerospace#20]
The attached aircraft causes Ferram Aerospace to report a positive Xu, which should be negative according to both the game and ferram's notes on stability derivatives. Since this doesn't happen with stock parts, and because I've used CKAN, I'm pretty sure everything is installed correctly. 

[S3 bugs.zip](https://github.com/blowfishpro/B9-Aerospace/files/293532/S3.bugs.zip)

**Comment by ZirconiumX** [comment]
I thought I had missed out on the 6.1.1 release, which fixes these issues. I haven't, so I'm reopening.

**Comment by blowfishpro** [comment]
I'm going to be on vacation for about a week but it would really help me in debugging this if you could do the following:

For each of the S3 parts you're using on that craft, place it in the editor by itself and verify that the FAR cross section line looks correct (i.e. not zero anywhere).  Also verify that the voxels look correct.  If any show up like this, let me know.

It's probably just a case of the collider being weird so FAR needs to use the visual mesh.  I fixed a bunch of these but I probably missed some.

**Comment by ZirconiumX** [comment]
Just realised I typo'd with the part category.

Okay, so, I think I've found the bug. Or a symptom at least. I haven't tested all the parts, but the S2 6m fuselage gives negative Xu in structural mode, but positive Xu in LF/LFO/MP. It also has a sharp negative start of the avg pressure coefficient curve.

**Comment by ZirconiumX** [comment]
![20160602170303_1](https://cloud.githubusercontent.com/assets/1503707/15752019/2dd55760-28e4-11e6-90a6-46f78cff96ea.jpg)

**Comment by blowfishpro** [comment]
I just tested this out and I can't find anything out of the ordinary.  Changes in stability derivatives are probably just due to the changing mass (noting that for a blunt body, drag is at the front).  You can get similar numbers for structural vs the fueled variants by emptying the tanks.  It appears to be the same on stock parts.  Am I missing something?

**Comment by blowfishpro** [comment]
Any update on this?  Does what I said make sense or do you think there are still issues?

**Comment by ZirconiumX** [comment]
I, uh, may have forgotten about this... >.>

I'll test it again in a few hours, but from what the FAR documentation
says, any condition that induces a positive Xu is a bad thing, since Xu is
basically drag, and drag making you accelerate is not a thing that exists,
no matter how hard people have tried.

**Comment by blowfishpro** [comment]
Closing for now, feel free to re-open if you get any additional info
