### ISSUE TITLE
only one connection point

### ISSUE THREAD

**Issue by flamedramon** [blowfishpro/B9-Aerospace#21]
Im new to this mod but from videos something seems wrong. The universal adapters only have one huge connection points instead of 4 small ones. I really dont know how to build anything with this.
![kerbal space program 7_3_2016 10_52_28 pm](https://cloud.githubusercontent.com/assets/20273939/16549804/f245b9f6-4170-11e6-946b-0bdff9e7fb73.png)

**Comment by blowfishpro** [comment]
I take it you figured out how to change the node setups?

**Comment by flamedramon** [comment]
Let's just pretend this never happened
