### ISSUE TITLE
Missing Parts to Ships

### ISSUE THREAD

**Issue by flamedramon** [blowfishpro/B9-Aerospace#22]
For some reason whenever i try to load the ships that come with this mod it says im missing parts. I tried reinstalling and thats not working. 
![kerbal space program 7_5_2016 5_11_59 pm](https://cloud.githubusercontent.com/assets/20273939/16600112/aca6c8fe-42d3-11e6-8873-cd7b2889e48a.png)

**Comment by blowfishpro** [comment]
I've kept them in the repository but they're not distributed in the download anymore because of this.  The landing gear broke in KSP 1.1, and the effort to revive them appears to be much more than it's worth.

**Comment by flamedramon** [comment]
Is there a way to load the ships without the landing gear so I can just attach my own

**Comment by blowfishpro** [comment]
You can download the B9 Aerospace 6.0.1 release and then copy GameData/B9_Aerospace_Legacy/Parts/Utility_Landing_Gear_HDG into your KSP install.  That will bring the landing gear back (though they won't actually work), so you an replace them and then re-save the craft.

**Comment by flamedramon** [comment]
K thanks. I really only had to replace them on one. They retract and extend fine but are bouncy and don't have breaks which is what I'm assuming is what you mean by it being broken. I suck too much to land anyway so it's not a big deal.

**Comment by blowfishpro** [comment]
That would be the bad behavior, yes.  The previous wheel implementation was completely removed, so all the wheel-specific stuff broke.
