### ISSUE TITLE
Other dl?

### ISSUE THREAD

**Issue by TrumpetMiner** [blowfishpro/B9-Aerospace#24]
In the FAQ on the forum it says you split into 2 downloads for the big blocky parts. Where is this download?

**Comment by blowfishpro** [comment]
If you look at the releases you will see 3 files:

- **B9_Aerospace_6-1-2.zip** - this is the main pack
- **B9_Aerospace_HX_6-1-2.zip** - this contains the large blocky parts
- **B9_Aerospace_Legacy_6-1-2.zip** - this contains some older parts
