### ISSUE TITLE
Some parts won't snap!

### ISSUE THREAD

**Issue by realcake** [blowfishpro/B9-Aerospace#27]
I recently downloaded your release for 1.1.3, but I am having some issues. I first noticed the issue when using the M-2 parts. I tried attaching it to a space-plane command module. It would snap into place, but as soon as a I tried to place the part the snap point would disappear, and would be back in my selection to be placed. It was impossible to place the part. Other parts also had this issue. I initially used the mod with KW rocketry, so I uninstalled it, but the problem continued. I then verified my game files, 7 files failed to validate, but that didn't solved the problem either. Any help would be appreciated greatly.

**Comment by blowfishpro** [comment]
So you are trying to attach using nodes?  Have you tried holding the option key?  That disables surface attachment so you will always snap to the nearest node.

**Comment by realcake** [comment]
Tried it, but no luck.

**Comment by blowfishpro** [comment]
Okay, could you describe exactly what parts you are trying to attach, how you are trying to attach them, what you expect the behavior to be, and what the behavior is?

**Comment by realcake** [comment]
I think it's hard for me to describe this, so [here ](https://gyazo.com/74ecf6a9db37b227e7a86ddc9dade136)is footage of the problem. [Continued](https://gyazo.com/d397a4c69c9c1daf142c79589e7faaac)... and [continued](https://gyazo.com/529ddf50371dc67ec3be9cef61595476)...and [here](https://gyazo.com/a51ff87d077f33fa9e537265be62247e). The problem is slightly different from the other day.

**Comment by Darknesshas1** [comment]
i've noticed it as well. Certain parts wont connect to others, like in mine the Massive payload hauling thruster only attaches to the Reactor part, which it will only allow be to place radially.

**Comment by blowfishpro** [comment]
This usually happens when something is throwing an exception.  Please provide logs so I can figure out what.

**Comment by blowfishpro** [comment]
Closing, if you still need help debugging and upload logs you can re-open
