### ISSUE TITLE
Very big issues on OSX

### ISSUE THREAD

**Issue by MK2X0** [blowfishpro/B9-Aerospace#29]
downloaded the mod accordingly as the description said and only a small part came out, all of it planes the mod is basicly broken in OSX/apple users could you please help?

**Comment by blowfishpro** [comment]
Nothing at all in this mod or its dependencies are platform specific.  If you're having issues, then something is installed incorrectly.  Please provide the following information:

1. Exactly what packages did you download from where and how did you install them?
2. What do you believe is missing?
3. Could you provide KSP's log?  [This post](http://forum.kerbalspaceprogram.com/index.php?showtopic=83212) will tell you how to find and upload it.

**Comment by MK2X0** [comment]
1. i've putten the package in the game data file not unpacked, works with all previous mods
2. only recieved HL plane parts, expecting the popular spaceships parts
3. will do later

**Comment by MK2X0** [comment]
further details 
installed 74,5 mb version (b9- 6-1-2)
previous attempts included HX

**Comment by blowfishpro** [comment]
I've never heard of mods being installed without unzipping them, and I don't think that's really a support way of installing.  Could you at least try extracting the packages and see if that changes anything (making sure to match the folder structure so that the contents of the package's GameData go into your KSP install's GameData).  Even if KSP can look in zipped packages, you would end up with things like duplicated bundled dependencies which could mess things up.  I could probably tell you exactly what works and what doesn't here if you provide the log.

As for the packages, the main pack contains most of the spaceplane parts, the legacy pack contains the older mk1/2 parts as well as wings, and the HX pack contains the blocky parts.  If you have craft that are missing parts, it's possible that those parts are in the legacy pack.

**Comment by MK2X0** [comment]
(The computer unzipped for me -_-)
as for the game data structure may be the problem

**Comment by blowfishpro** [comment]
The folder structure definitely matters.  Many things depend on being at an exact path (relative to your KSP root directory).  If the structure is wrong, then parts will be missing.

**Comment by MK2X0** [comment]
then please show the correct structure wthim the folder
by the way there were only tetragon pieces may that be the problem?

**Comment by blowfishpro** [comment]
The contents of the GameData folder inside the package should be copied into your existing GameData folder.  So you will end up with something like

```
GameData
    B9AnimationModules
    B9PartSwitch
    B9_Aerospace
    Firespitter
    JSI
    SmokeScreen
    Squad
    ModuleManager 2.6.25.dll
    ...
```

**Comment by MK2X0** [comment]
ok all good! 
thanks
by the way 99% of mods work woth only  the packed unzipped folder, this doesnt

**Comment by MK2X0** [comment]
but wait just a question b9 standard and HX have both animation and smokescreen and both do not accepet others are both equaall?

**Comment by MK2X0** [comment]
ok HX pieces are missing but i fear changing name will break it even more

**Comment by blowfishpro** [comment]
B9_Aerospace_HX would be placed under GameData like everything else.  You only need one copy of each dependency.

**Comment by blowfishpro** [comment]
It sounds like you might have your issues resolved, but I'm still trying to figure out how you installed things initially.  The basic install procedure should be as following

* Download mod zip
* Unzip it
* Copy contents of unzipped folder's GameData into KSP's existing GameData

What did you do differently?

**Comment by MK2X0** [comment]
thats the problem they they have the same title and putting both will make the computer ask if you want to replace and if not its not placed, do i put hx documents on on the standard animation and smokescreen folder or what?

**Comment by blowfishpro** [comment]
B9_Aerospace and B9_Aerospace_HX both have dependencies in common, so they are included in both packages.  You only need to keep one version of each.  Does that make sense?

**Comment by MK2X0** [comment]
still i dont see any HX cockpit

**Comment by MK2X0** [comment]
the preview of the mod has a bridge and other small pieces

**Comment by MK2X0** [comment]
but otherwise i do precive

**Comment by blowfishpro** [comment]
There was never an HX cockpit.  Not sure what image you're referring to.

**Comment by MK2X0** [comment]
ok then thanks
