### ISSUE TITLE
Parts Wont Show Up

### ISSUE THREAD

**Issue by TheSmartBucket** [blowfishpro/B9-Aerospace#30]
I installed the ships folder,and the gamedata folders into gamedata and ships but the parts wont show up.

**Comment by TheSmartBucket** [comment]
Nevermind.

**Comment by TheSmartBucket** [comment]
It just doesent work,I dont find the parts.

**Comment by blowfishpro** [comment]
There shouldn't be any ships folder in more recent releases.  Did you download the most recent release from here?: https://github.com/blowfishpro/B9-Aerospace/releases

**Comment by Joeh1234** [comment]
I beileve that TheSmartBucket is talking about if you download the source code there is a ship folder

**Comment by blowfishpro** [comment]
If you're just trying to install and play B9, you shouldn't do that.  Stick to the release packages unless you have a good reason not to.

**Comment by Joeh1234** [comment]
So I shouldn't download the source code but only download the three files above it (the normal b9, the b9 hxparts  and the b9 legacy

**Comment by blowfishpro** [comment]
Yes, again unless you have a specific reason not to.
