### ISSUE TITLE
The old cockpits wont show up no matter what i do please help

### ISSUE THREAD

**Issue by FixB9pls** [blowfishpro/B9-Aerospace#36]
ive tried normal b9 legacy and hx but the old cockpits i love wont show up so i cant build awsome planes (and yes it was the latest version) anyway please help me these cockpits mean so much to me

**Comment by blowfishpro** [comment]
Are you on KSP 1.2?  If so, you will just have to wait for a new B9 version (old version is known to not work on 1.2, this is mentioned in the thread).  If not, please provide the normal debugging information, i.e. KSP's log.

**Comment by FixB9pls** [comment]
ok so the cockpits are just missing because im on 1.2 right?

**Comment by blowfishpro** [comment]
Many things will be broken if you use the most recent release of B9 on 1.2 - please stick to 1.1.3 until there is an official release.

**Comment by FixB9pls** [comment]
thanks man
