### ISSUE TITLE
Vtol engines instanly overheat when toggle hover

### ISSUE THREAD

**Issue by Seitekful** [blowfishpro/B9-Aerospace#39]
when i press toggle hover the engines overheat instantly. sometime i have to try increase hover height and they explode... 

am i missing something like a special radiors setup? or is it just broken?

**Comment by blowfishpro** [comment]
This is the fault of a firespitter module which probably has some really old broken code in it.  I might just remove the "hover" feature since I've seen a few complaints about this.

**Comment by Seitekful** [comment]
nooo dont remove this funktion! these vtol engines are the best (when they work ofcourse)

i modding the cfg: 
-set the max temp to crazy values
-turn off exhaust heat 
-turn of overheat

wich resultet in the engine not overheating, but aswell not hovering... 
the  hover funktion is so super duper sweet i have no words <3

**Comment by blowfishpro** [comment]
I wouldn't be removing the VTOL engines entirely, just the hover function.  Firespitter's code is old, and probably has had these issues for a while.  I'm not sure what else to do short of rewriting it.

**Comment by blowfishpro** [comment]
The module causing problems has been removed.  Unfortunately this means that the hover function has been removed.
