### ISSUE TITLE
Can we please get some more parts from the 5.0.0 version?

### ISSUE THREAD

**Issue by TheAmazingSpy** [blowfishpro/B9-Aerospace#4]
I have looked at this mod, and realised that some parts are missing from 5.0.0, so could we please have some more parts moved over to be compatible? I have tested with both versions mixed together, and it works *pretty* well, except some things like some of the wings don't register as being aerodynamic, and don't contribute to the lift, et cetera. So if this is possible, could this happen?

**Comment by blowfishpro** [comment]
With a few minor exceptions, everything that was in previous versions is in 6.0 - many things have moved to the legacy pack, but they are still there (the exception is the engine pylons, which are not switchable options on the engines).

**Comment by TheAmazingSpy** [comment]
Don't worry, I downloaded straight from the code page (not releases) and it works perfectly. And I love the IVAS too, but some of them I can't mange to turn them on, do you know how to turn them on (when they're not displaying tetragon on the screen, just black)

**Comment by blowfishpro** [comment]
It's been a while since I flew on IVA, but I believe you just press any of the buttons on the top? of the screen to go to a particular screen from the start screen.
