### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by Isenderen** [blowfishpro/B9-Aerospace#40]
Basically the title says it all. If i try to use any parts from tetragon industries in game, they will look like they will attach, but then i can still drag them until i click again and then it will be unmoveable except for when you click on the root part. Also when ships are spawned with b9 parts they will spazz out before exploding, killing the skybox to show space, then the game will crash without a crash log. If this is an unknown issue please let me know, it wont let me upload my log since its too big.

**Comment by blowfishpro** [comment]
Proper debugging information please!  I can't help you without a log

**Comment by Temido2222** [comment]
Are you running 1.1?

**Comment by Isenderen** [comment]
I am running 1.1.3 with this mod list:
![screenshot 77](https://cloud.githubusercontent.com/assets/18625097/20034384/d249dbac-a370-11e6-9f77-d34851399dc2.png)

**Comment by Isenderen** [comment]
[KSP.txt](https://github.com/blowfishpro/B9-Aerospace/files/573574/KSP.txt)
heres the log file. youll just have to rename it to .txt because github wouldnt let me send a .log file.

**Comment by blowfishpro** [comment]
You have ModuleManager 2.7.1 installed.  That will only work with KSP 1.2.

There also seems to be something weird going on with the Firespitter plugin.  There's one in RetroFuture (which hasn't been updated in ages IIRC) and another where it should be.  I recommend removing both and reinstalling the latest version for KSP 1.1.3 ([v7.3.0](https://github.com/snjo/Firespitter/releases/tag/v7.3.0))

**Comment by blowfishpro** [comment]
Closing, feel free to re-open if you need any more help
