### ISSUE TITLE
Some engines ignore crossfeed setting and always draw fuel 

### ISSUE THREAD

**Issue by Fl4shblade** [blowfishpro/B9-Aerospace#45]
Ignore: SABRE M and S, CMF56, TFE731

Works: VA1, VS1, D30F7, F119, L2 Atlas

**Comment by blowfishpro** [comment]
Best guess I have is `resourceFlowMode = STAGE_PRIORITY_FLOW` (bad) vs `resourceFlowMode = STAGE_STACK_FLOW_BALANCE` (good) (spot checking a few of the engines suggest that the ones that work/don't are divided along these lines).  I'll check when I have a chance...

**Comment by Fl4shblade** [comment]
I am giving this a try now

**Comment by blowfishpro** [comment]
Fixed by #46
