### ISSUE TITLE
MK2B probe core internal antenna

### ISSUE THREAD

**Issue by Fl4shblade** [blowfishpro/B9-Aerospace#47]
The internal antenna of the MK2B probe core is not initializing in the flight scene. The information of the antenna is properly displayed in the SPH, therefor it is unlikely that the config file has a mistake in it. Putting an extra antenna on a craft with the core also doesn't fix the problem and leaves that craft only partially controllable as if connection with the KSC was lost.

**Comment by blowfishpro** [comment]
Figured it out, needed `vesselType = Probe`
