### ISSUE TITLE
Cannot load on startup

### ISSUE THREAD

**Issue by Trann18** [blowfishpro/B9-Aerospace#5]
I can't load B-9 Aerospace all the way. When it's loading on startup, I'm stuck on [this](https://gyazo.com/2b42159c5656c20e0f2a605e4ee9ce81) and I can't find a way to fix it. Can I get some help?

**Comment by blowfishpro** [comment]
1. What version of KSP are you on?  For B9 6.0.1, it should be KSP 1.0.5.
2. I think support requests like this are better kept on the forums.
3. No way to tell what's going on without your logs (unless you're on the wrong version of KSP).  Instructions on how to find them are [here](http://forum.kerbalspaceprogram.com/index.php?showtopic=83212).

**Comment by MakeLord** [comment]
I think he is on the newest version (1.1) as I'm stuck on the same part...

**Comment by blowfishpro** [comment]
No official version has been released for 1.1 yet.  You can get it working if you download a bunch of stuff manually, but if you're not quite sure what you're doing it's probably best to just hold off for the moment.

**Comment by MakeLord** [comment]
yea. I'll wait for the update...
