### ISSUE TITLE
 Parts falling apart and clipping *on launch*

### ISSUE THREAD

**Issue by SkriptedRogue** [blowfishpro/B9-Aerospace#52]
This is a repost from the old github. I have gotten the new mods. So i've been trying to recreate a somewhat old build, called the cube. I've attached images that show what it looks like in the creator and what it looks like on launch. I don't think this is a fault of mine but if it is, please notify me on how to fix it.
![chrome_2017-03-19_13-15-25](https://cloud.githubusercontent.com/assets/26527486/24084113/8d885a9e-0cba-11e7-842a-08046df451ed.png)
![ksp_x64_2017-03-19_13-18-52](https://cloud.githubusercontent.com/assets/26527486/24084122/b02e097c-0cba-11e7-8037-4e7bb826a144.png)

**Comment by SkriptedRogue** [comment]
I have also built another craft that flops around too (even with some struts)

**Comment by blowfishpro** [comment]
Oh, is the problem that the parts are detaching and falling through each other, or that the joints are just floppy?  If it's the second one, that's just the nature of joints in KSP, particularly surface attachment joints on very large parts.

There are a couple of ways to work around that.  One is to use autostruts.  This is an option that can be made visible by enabling "advanced tweakables" in one of KSP's settings menus (forget exactly which one).  You can then use the autostrut option in the editor to attach things more rigidly.

The other option is to get the Kerbal Join Reinforcement mod (highly recommended for B9 in general) which strengthens all joints automatically.

**Comment by SkriptedRogue** [comment]
I will explain it. I launch then the parts look like they are piviting
around one point (the connection in between), I can get a gif if you need
it.






*-Ted/Rouge*

**Comment by SkriptedRogue** [comment]
Pivoting*






*-Ted/Rouge*
