### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by bghyt** [blowfishpro/B9-Aerospace#55]
on ksp 1.3 and it crashes when it gets to the part adaptor c125 i have a clean install and only the base b9 installed as i thorght the other packeges were causeing the crash but heres my logs

[output_log.txt](https://github.com/blowfishpro/B9-Aerospace/files/1151087/output_log.txt)

**Comment by blowfishpro** [comment]
If you're running on 1.3, you need to update all of the dependencies individually (the ones in the download will *not* work).  They're all listed, with links, in the first post of the B9 thread.  If you update them all and still get the crash you can post your updated log and I'll take a look again.

**Comment by bghyt** [comment]
thank you
