### ISSUE TITLE
The S3 cockpit only has a maximum crew capacity of 1 kerbal.

### ISSUE THREAD

**Issue by WHOGX5** [blowfishpro/B9-Aerospace#57]
As the title says, even though the S3 cockpit has both a front and a rear seat, only the front one is usable. The part crew cap in-game was 1, so I checked the S3 cockpit .cfg file and the crew cap was indeed set to 1 so I don't know if this was intentional or just a typo, but at least it doesn't seem to be a bug per se.

**Comment by blowfishpro** [comment]
I think this is mostly because the IVA was a placeholder - it uses the Mk2 legacy cockpit IVA which as two seats
