### ISSUE TITLE
B9 crashed with RemoteTech

### ISSUE THREAD

**Issue by Ordpus** [blowfishpro/B9-Aerospace#59]
I mean, literally, B9 crashes with RT(include Legacy, HX, partswitch and animationparts) on my computer. Cannot figure out how to solve.
[error.log](https://github.com/blowfishpro/B9-Aerospace/files/1345978/error.log)
[output_log.txt](https://github.com/blowfishpro/B9-Aerospace/files/1345979/output_log.txt)

[crash.zip](https://github.com/blowfishpro/B9-Aerospace/files/1345980/crash.zip)
[KSP.log](https://github.com/blowfishpro/B9-Aerospace/files/1345982/KSP.log)

**Comment by blowfishpro** [comment]
Looks like you have an out-of-date version of the Firespitter plugin.  Updating that will likely fix the crash.

**Comment by blowfishpro** [comment]
Also looks like you don't have SmokeScreen or RasterPropMonitor installed.  Those are dependencies of B9 (although their absence won't cause a crash)

**Comment by Ordpus** [comment]
....I just forgot to copy the dependencies from my full pack, but the problem is when I add RT into my pack(which can run smoothly) with B9, it crashes.
[crash.zip](https://github.com/blowfishpro/B9-Aerospace/files/1346053/crash.zip)
[error.log](https://github.com/blowfishpro/B9-Aerospace/files/1346054/error.log)
[output_log.txt](https://github.com/blowfishpro/B9-Aerospace/files/1346052/output_log.txt)
[KSP.log](https://github.com/blowfishpro/B9-Aerospace/files/1346055/KSP.log)

**Comment by blowfishpro** [comment]
Oh, looks like Firespitter just reports its version weirdly

But now that I look again, it looks like RemoteTech is in fact out of date.  You have 1.8.6, which was for KSP 1.2.2.  The latest is 1.8.8, which is for KSP 1.3

**Comment by Ordpus** [comment]
Thank you it works. It's so stupid of me that I downloaded the wrong version without even noticing :)
