### ISSUE TITLE
wings not being wings! (sorry blowfish)

### ISSUE THREAD

**Issue by antimatter001** [blowfishpro/B9-Aerospace#64]
[ModuleManager.txt](https://github.com/blowfishpro/B9-Aerospace/files/1372796/ModuleManager.txt)
[output_log.txt](https://github.com/blowfishpro/B9-Aerospace/files/1372807/output_log.txt)

yeahhhhh sorry for any problems you come across with my mess install :/

**Comment by blowfishpro** [comment]
AoATech has a config that's making ModuleManager think FAR is installed when it isn't

In `AoATech/Parts/Aero/TestFin/TESTFin.cfg` there's a patch `@PART[AoAero.TESTFin]:FOR[FerramAerospaceResearch] { }`

You should let the author of that mod know about it

**Comment by antimatter001** [comment]
is there a work around for now or can i remove it...? thanks again blowfish!
