### ISSUE TITLE
B9partswitch causing CTD

### ISSUE THREAD

**Issue by CapSierra** [blowfishpro/B9-Aerospace#7]
(THIS IS TESTED USING THE LATEST VERSION OF THE PLUGIN ONLY AND ANOTHER MOD WITH MESH SWITCHING PARTS)
Extensive use of mesh-switched parts in the editor is causing a crash-to-desktop at the windows level (ksp_x64.exe has stopped working window pops up). Exact repro steps are proving difficult, as the crash seems to induce semi-erratically. Output logs from last induced crash on an isolated install with only the latest version of the plugin, KSP 1.1 running x64, and a set of mesh switching parts (NF construction specifically) are included below.

[output_log.txt](https://github.com/blowfishpro/B9-Aerospace/files/233630/output_log.txt)

**Comment by blowfishpro** [comment]
I'm pretty sure this is a stock problem.  No exception is thrown, the game just crashes.  I've experienced it myself in stock, seen it reported on the Squad bugtracker, and a couple of people also reported it in the KW thread.  I don't think there's anything I can do about it.
