### ISSUE TITLE
fuel tanks not fuel tanks

### ISSUE THREAD

**Issue by kspbro** [blowfishpro/B9-Aerospace#70]
I got the mod and the change fuel tank option isn't there

**Comment by blowfishpro** [comment]
Very likely B9PartSwitch is missing or installed incorrectly.  Try reinstalling it.

**Comment by kspbro** [comment]
oh b9 part switch is a thing

**Comment by blowfishpro** [comment]
It comes with the release and is stated as a dependency.  B9 will not work without it.
