### ISSUE TITLE
Missing agent title

### ISSUE THREAD

**Issue by MaximeBrean** [blowfishpro/B9-Aerospace#71]
The agency provided by this mod doesn't have any title entry. It's not game breaking but it produce weird mission texts and the agency doesn't show up in the filtering tab of the VAB/SPH.

**Comment by MaximeBrean** [comment]
Hum, unless I have missed something, the title has to be define as the `title` property, like `title = Tetragon Projects`

**Comment by blowfishpro** [comment]
Ugh, copy paste error
