### ISSUE TITLE
Props is showing up in NetKAN with KSP max 1.4.2

### ISSUE THREAD

**Issue by Darael** [blowfishpro/B9-Aerospace#78]
I can't immediately work out what in the netkan files is causing this, but having the knock-on effect of making everything that depends on B9-props, including the other B9 packs, show up as incompatible in CKAN for 1.4.3 and later.

**Comment by blowfishpro** [comment]
Oh I see what's wrong.  I changed how the files are named, which means that I need to change the regular expression in the `$kref`.  I did it for B9 but not props.
