### ISSUE TITLE
How to avtivate cockpit inner screen?

### ISSUE THREAD

**Issue by Multisim1000** [blowfishpro/B9-Aerospace#86]
My KSP version is 1.7 and I have  downloaded the B9-master zip and unpacked all the files into the root folder. However, for those B9 cockpits, the cockpits' inner screens don't work. I cannot control the inner screens and other buttons. Can you help me? What should I do to make them work?

**Comment by blowfishpro** [comment]
Do you have the latest RasterPropMonitor installed?

**Comment by Multisim1000** [comment]
Nope, what's that and where can I download it?

**Comment by Multisim1000** [comment]
How to installed the latest monitor?

**Comment by blowfishpro** [comment]
None of the dependencies are included in the repo.  They’re included in release packages but not if you download master.  They’re all listed in the first post of the B9 thread.  They might be linked too but if not you can definitely search for each one at that point.

**Comment by Multisim1000** [comment]
thx, problem solved.
