### ISSUE TITLE
How do I download this mod??? (plus please update to 1.6)

### ISSUE THREAD

**Issue by MinehutServer** [blowfishpro/B9-Aerospace#87]
I have no idea how to download this mod, every tutorial I have seen is outdated and please link me to a updated tutorial.

readme doesnt make sense at all and I dont understand it.

**Comment by blowfishpro** [comment]
There is no formal tutorial.  If you understand the general structure of KSP mods though you should be able to get it working on KSP 1.6 - the important part being that the dependencies included in the latest release package are not the correct versions.  So you will have to get the correct versions of each of those.

**Comment by blowfishpro** [comment]
Also, next update will be for KSP 1.7
