### ISSUE TITLE
Outdated CurseForge redistribution

### ISSUE THREAD

**Issue by Monniasza** [blowfishpro/B9-Aerospace#90]
Newest version on CurseForge [B9_Aerospace_Pack_R5-2-8.zip](https://www.curseforge.com/kerbal/ksp-mods/b9-aerospace-5-2-8/files) is outdated.

**Comment by blowfishpro** [comment]
I don’t have access to update anything on CurseForge, and those who do aren’t around anymore

**Comment by blowfishpro** [comment]
I'll add that I would do something about this if I could.  But CurseForge isn't really used much by the modding community anymore anyway.  Releases are done here at Github, which you managed to find anyway.
