### ISSUE TITLE
MechJeb  and TweakScale stop working

### ISSUE THREAD

**Issue by Monniasza** [blowfishpro/B9-Aerospace#91]
When i installed B9-Aerospace, MechJeb and TweakScale disappeared

**Comment by blowfishpro** [comment]
Double check that you’ve installed everything correctly.  There should not be any interaction.

If that fails I need to see KSP’s log

**Comment by Monniasza** [comment]
I have both modifications.
[output_log.txt](https://github.com/blowfishpro/B9-Aerospace/files/3217383/output_log.txt)

**Comment by blowfishpro** [comment]
Well you don't have any of B9's dependencies installed, I would expect stuff to be broken.  This includes ModuleManager which I think is a requirement for Tweakscale.
