### ISSUE TITLE
Inverted HUD cameras

### ISSUE THREAD

**Issue by ncanceill** [blowfishpro/B9-Aerospace#92]
**Description**
HUD cameras ("APFD") are displayed upside-down

**How to reproduce**
 KSP 1.7.0.2483 (Windows x64) with DirectX3D11, B9 Aerospace 6.5.2 and RasterPropMonitor 0.30.6
Load a vessel with a B9 cockpit, go IVA and use the APFD button to display one of the two internal cameras with HUD included

**Root cause**
This only affects the APFD displays with internal cameras (specifically `syntneticvision` (sic) and `syntneticvisionL`  (sic)), see https://github.com/blowfishpro/B9-Aerospace/blob/v6.5.2/GameData/B9_Aerospace/Props/B9_MFD/B9_MFD.cfg#L206-L290
The other displays including cameras (docking, internal and external cameras, take off assist, landing assist) are unaffected
The big difference is that the former use RasterPropMonitor's `JSIHeadsUpDisplay.RenderHUD` (because they include a HUD) and the latter use `JSISteerableCamera.RenderCamera`
This seems to be related to a number of issues in RasterPropMonitor (see [#659](https://github.com/Mihara/RasterPropMonitor/issues/659) and linked issues) but they are reportedly fixed, and I heard that the development has stopped anyway
I have no idea whether it would be possible to fix or even mitigate from the B9 props config files

I understand that the problem should not occur with OpenGL, but I have tried and it breaks my game bad, so no much luck there
I do not know the code of RasterPropMonitor and I do not know anything about Unity engine, so I am afraid I cannot help a lot. Should I ask on the forum thread if anyone else has seen this issue?

---

PS: Hi @blowfishpro! I run several of your mods, thanks for all the work :-)

**Comment by blowfishpro** [comment]
I see the issue too.  I'm unfortunately not too familiar with RPM configuration, so I don't know what the fix would be even if there was one.

**Comment by ncanceill** [comment]
I confirm that this is related to the aforementioned RPM issue, as it can be fixed by disabling anti-aliasing

I will go ask about it over there

**Comment by ncanceill** [comment]
Reported as [#684](https://github.com/Mihara/RasterPropMonitor/issues/684), let us hope they can help

**Comment by MOARdV** [comment]
This is, indeed, a bug in RPM,  However, I am no longer working on RPM.  Ideally, B9 would migrate to MAS - it would certainly allow for some much more impressive IVA experiences. I also fully understand that that's a lot of work, especially since B9 uses some custom prop configurations.

**Comment by JonnyOThan** [comment]
Note this is fixed in my fork (mainly due to the new Unity version) for KSP 1.8:
https://github.com/JonnyOThan/RasterPropMonitor/releases/tag/v0.31.0

**Comment by blowfishpro** [comment]
Fixed indeed
