### ISSUE TITLE
S2 Cockpit RCS effect always on

### ISSUE THREAD

**Issue by Tonas1997** [blowfishpro/B9-Aerospace#94]
As stated in the title, the S2 cockpit's RCS thrusters have a permanent "running" effect which I _suspect_ to caused by these config nodes:

`EFFECTS
    {
        running
        {
            AUDIO_MULTI_POOL
            {
                channel = Ship
                clip = sound_rocket_mini
                volume = 0.0 0.0
                volume = 0.02 0.1
                volume = 0.5 0.1
                volume = 1.0 0.1
                pitch = 0.0 0.75
                pitch = 1.0 1.5
                loop = true
            }
            MODEL_MULTI_PARTICLE
            {
                modelName = Squad/FX/Monoprop_small
                transformName = RCSthruster
                emission = 0.0 0.0
                emission = 0.1 0.0
                emission = 1.0 1.0
                speed = 0.0 0.8
                speed = 1.0 1.0
                localRotation = -90, 0, 0
                localPosition = 0, 0.05, 0
            }
        }
    }`

**Comment by blowfishpro** [comment]
They look fine to me.  Will need full logs and ModuleManager.ConfigCache to see what's going on in your install.

**Comment by blowfishpro** [comment]
Closing due to lack of follow-up
