### ISSUE TITLE
CKAN version information is incorrect / 1.8 compat request

### ISSUE THREAD

**Issue by B-Knight49** [blowfishpro/B9-Aerospace#96]
From what I've read, the mod works on more recent versions of KSP (excluding 1.8). CKAN, however, lists B9 as incompatible with anything after 1.5.x and likely references outdated dependencies. For longevity sake, could B9 Aerospace (and its child mods like Legacy/HX) be updated on CKAN? 

On a similar note; 1.8 compatibility would be appreciated. Firespitter is the only dependency currently not up-to-date with 1.8 with RPM largely being redundant now (replaced with MAS) and being optional regardless - right? Since it only controls some animations in IVA view?

**Comment by blowfishpro** [comment]
My preferred method is just to do a new release with an updated KSP version.  Not much work, just haven't gotten around to it.

1.8 - if Firespitter isn't up to date I'm not going to do it yet.  You wouldn't be able to install via CKAN anyway.

RPM/MAS - The B9 props depend on RPM, if you tried to install B9 with out RPM I'd imagine KSP would complain a bunch and I don't know what would actually show up in IVA view (broken props or nothing?)

The props would have to be either ported to MAS or replaced with something more standard.  I have neither the skill nor time to do that (definitely accepting submissions for it though)

**Comment by advaithm** [comment]
hey firespitter released a version for 1.8

**Comment by blowfishpro** [comment]
That still leaves RPM...

**Comment by advaithm** [comment]
yeah i believe that he guy who made RPM is having issues porting it to 1.8 due to bugs such as inverted y axis on the texture

**Comment by JonnyOThan** [comment]
New update for RPM on KSP 1.8 here: https://github.com/JonnyOThan/RasterPropMonitor/releases/tag/v0.31.0
Should be on CKAN pretty soon.

**Comment by blowfishpro** [comment]
Will release for 1.8 shortly now that dependencies are there

**Comment by B-Knight49** [comment]
Forgive me mate, did you update the CKAN info? It still says incompatible for me.

**Comment by blowfishpro** [comment]
Not yet.  When it happens it will be a new release of B9
