### ISSUE TITLE
B9PartSwitch - Serious Warning?

### ISSUE THREAD

**Issue by MeanGene1016** [blowfishpro/B9-Aerospace#97]
Why do I get a popup during the loading process in KSP that reads... "B9PartSwitch - Serious Warning" and below it says "More than one module can't manage a part's crashTolerance" and "Please see KSP's log for additional details" this just started happening yesterday when I tried to load a game. Is anyone else having the same issue?
![20191130_083620](https://user-images.githubusercontent.com/58365264/69901904-34f36f80-134d-11ea-93c0-c4a7c74695a3.jpg)

**Comment by MeanGene1016** [comment]
I didn't install any new mods or update any of my existing mods before this popped up! Steam updated like always but that's it and then this!

**Comment by blowfishpro** [comment]
(1) As it says I need your log to figure out what’s going on.  Please include GameData/ModuleManager.ConfigCache as well

2) Modding your steam install is a bad idea precisely because of auto updates.  Copy KSP somewhere else and mod there

**Comment by blowfishpro** [comment]
3) This isn’t actually the repo for B9PartSwitch

**Comment by blowfishpro** [comment]
No response, closing
